# Default settings that apply to all drivers
default:
  max_actions: 10

# OpenAI driver configuration
openai:
  model: gpt-4.1-nano
  temperature: 0.0
  max_tokens: 1000
  response_format: json_object

# Anthropic driver configuration (placeholder for future implementation)
anthropic:
  model: claude-3-haiku-20240307
  temperature: 0.0
  max_tokens: 1000

# Ollama driver configuration
ollama:
  model: mistral-nemo:12b
  temperature: 0.0
  max_tokens: 1000

# OpenAI + LangChain configuration (placeholder for future implementation)
openai_langchain:
  model: gpt-4.1-nano
  temperature: 0.0
  max_tokens: 1000
